{{- if .Values.loadGenerator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nimbusguard.fullname" . }}-load-generator
  labels:
    {{- include "nimbusguard.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "4"
spec:
  replicas: {{ .Values.loadGenerator.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nimbusguard.name" . }}
      app.kubernetes.io/component: load-generator
  template:
    metadata:
      labels:
        {{- include "nimbusguard.labels" . | nindent 8 }}
        app.kubernetes.io/component: load-generator
    spec:
      containers:
        - name: load-generator
          image: "{{ .Values.loadGenerator.image.repository }}:{{ .Values.loadGenerator.image.tag }}"
          imagePullPolicy: {{ .Values.loadGenerator.image.pullPolicy }}
          resources:
            {{- toYaml .Values.loadGenerator.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.loadGenerator.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.loadGenerator.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.loadGenerator.affinity | nindent 8 }}
{{- end }}
